
package com;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-12-07T16:03:41.311+02:00
 * Generated source version: 3.1.1
 * 
 */
public final class AvayaVoicePortalServicesWS_AvayaVoicePortalServicesWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://kz.kcell.apps.pentagon.coda.ws", "avayaVPServices");

    private AvayaVoicePortalServicesWS_AvayaVoicePortalServicesWSPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = AvayaVPServices.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AvayaVPServices ss = new AvayaVPServices(wsdlURL, SERVICE_NAME);
        AvayaVoicePortalServicesWS port = ss.getAvayaVoicePortalServicesWSPort();  
        
        {
        System.out.println("Invoking addBusinessProductNotifyAVP...");
        String _addBusinessProductNotifyAVP_msisdn = "";
        Long _addBusinessProductNotifyAVP_bpId = null;
        try {
            port.addBusinessProductNotifyAVP(_addBusinessProductNotifyAVP_msisdn, _addBusinessProductNotifyAVP_bpId);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (AddPromoException_Exception e) { 
            System.out.println("Expected exception: AddPromoException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputDataException_Exception e) { 
            System.out.println("Expected exception: InvalidInputDataException has occurred.");
            System.out.println(e.toString());
        } catch (AddBusinessProductException_Exception e) { 
            System.out.println("Expected exception: AddBusinessProductException has occurred.");
            System.out.println(e.toString());
        } catch (IllegalChannelException_Exception e) { 
            System.out.println("Expected exception: IllegalChannelException has occurred.");
            System.out.println(e.toString());
        } catch (BusinessProductConfigException_Exception e) { 
            System.out.println("Expected exception: BusinessProductConfigException has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking enableAutoExtraBalanceAVP...");
        String _enableAutoExtraBalanceAVP_msisdn = "";
        try {
            port.enableAutoExtraBalanceAVP(_enableAutoExtraBalanceAVP_msisdn);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking changeTariffFreeAVP...");
        String _changeTariffFreeAVP_msisdn = "";
        Long _changeTariffFreeAVP_tariffId = null;
        try {
            port.changeTariffFreeAVP(_changeTariffFreeAVP_msisdn, _changeTariffFreeAVP_tariffId);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (ProductAlreadySoldException_Exception e) { 
            System.out.println("Expected exception: ProductAlreadySoldException has occurred.");
            System.out.println(e.toString());
        } catch (TariffChangeException_Exception e) { 
            System.out.println("Expected exception: TariffChangeException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (ProductNotFoundException_Exception e) { 
            System.out.println("Expected exception: ProductNotFoundException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addBusinessProductNotifyNewAVP...");
        String _addBusinessProductNotifyNewAVP_msisdn = "";
        Long _addBusinessProductNotifyNewAVP_bpId = null;
        Boolean _addBusinessProductNotifyNewAVP_resubscribe = null;
        try {
            port.addBusinessProductNotifyNewAVP(_addBusinessProductNotifyNewAVP_msisdn, _addBusinessProductNotifyNewAVP_bpId, _addBusinessProductNotifyNewAVP_resubscribe);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (AddPromoException_Exception e) { 
            System.out.println("Expected exception: AddPromoException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputDataException_Exception e) { 
            System.out.println("Expected exception: InvalidInputDataException has occurred.");
            System.out.println(e.toString());
        } catch (AddBusinessProductException_Exception e) { 
            System.out.println("Expected exception: AddBusinessProductException has occurred.");
            System.out.println(e.toString());
        } catch (IllegalChannelException_Exception e) { 
            System.out.println("Expected exception: IllegalChannelException has occurred.");
            System.out.println(e.toString());
        } catch (BusinessProductConfigException_Exception e) { 
            System.out.println("Expected exception: BusinessProductConfigException has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking grantMobileCreditAVP...");
        String _grantMobileCreditAVP_msisdn = "";
        try {
            port.grantMobileCreditAVP(_grantMobileCreditAVP_msisdn);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputDataException_Exception e) { 
            System.out.println("Expected exception: InvalidInputDataException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking mobileCreditEligibleAVP...");
        String _mobileCreditEligibleAVP_msisdn = "";
        try {
            String _mobileCreditEligibleAVP__return = port.mobileCreditEligibleAVP(_mobileCreditEligibleAVP_msisdn);
            System.out.println("mobileCreditEligibleAVP.result=" + _mobileCreditEligibleAVP__return);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputDataException_Exception e) { 
            System.out.println("Expected exception: InvalidInputDataException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking isInRoaming...");
        String _isInRoaming_arg0 = "";
        try {
            Boolean _isInRoaming__return = port.isInRoaming(_isInRoaming_arg0);
            System.out.println("isInRoaming.result=" + _isInRoaming__return);

        } catch (CODAHLRException_Exception e) { 
            System.out.println("Expected exception: CODAHLRException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking unbarrByPuk...");
        String _unbarrByPuk_msisdn = "";
        String _unbarrByPuk_comments = "";
        String _unbarrByPuk_channel = "";
        String _unbarrByPuk_puk = "";
        try {
            port.unbarrByPuk(_unbarrByPuk_msisdn, _unbarrByPuk_comments, _unbarrByPuk_channel, _unbarrByPuk_puk);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (MsisdnBarException_Exception e) { 
            System.out.println("Expected exception: MsisdnBarException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (IllegalChannelException_Exception e) { 
            System.out.println("Expected exception: IllegalChannelException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputDataException_Exception e) { 
            System.out.println("Expected exception: InvalidInputDataException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getRoamingStateAVP...");
        String _getRoamingStateAVP_msisdn = "";
        try {
            boolean _getRoamingStateAVP__return = port.getRoamingStateAVP(_getRoamingStateAVP_msisdn);
            System.out.println("getRoamingStateAVP.result=" + _getRoamingStateAVP__return);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (SoldProductsRetrivalException_Exception e) { 
            System.out.println("Expected exception: SoldProductsRetrivalException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking blockAVP...");
        String _blockAVP_msisdn = "";
        try {
            port.blockAVP(_blockAVP_msisdn);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (MsisdnBarException_Exception e) { 
            System.out.println("Expected exception: MsisdnBarException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (IllegalChannelException_Exception e) { 
            System.out.println("Expected exception: IllegalChannelException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputDataException_Exception e) { 
            System.out.println("Expected exception: InvalidInputDataException has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking checkSubscriberInRoaming...");
        String _checkSubscriberInRoaming_arg0 = "";
        try {
            Boolean _checkSubscriberInRoaming__return = port.checkSubscriberInRoaming(_checkSubscriberInRoaming_arg0);
            System.out.println("checkSubscriberInRoaming.result=" + _checkSubscriberInRoaming__return);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (CODAHLRException_Exception e) { 
            System.out.println("Expected exception: CODAHLRException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getBalanceAVP...");
        String _getBalanceAVP_msisdn = "";
        try {
            AvayaBalanceDTO _getBalanceAVP__return = port.getBalanceAVP(_getBalanceAVP_msisdn);
            System.out.println("getBalanceAVP.result=" + _getBalanceAVP__return);

        } catch (CODAInternalFailure_Exception e) {
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) {
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addServiceAVP...");
        String _addServiceAVP_msisdn = "";
        Integer _addServiceAVP_serviceId = null;
        try {
            port.addServiceAVP(_addServiceAVP_msisdn, _addServiceAVP_serviceId);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (AddPromoException_Exception e) { 
            System.out.println("Expected exception: AddPromoException has occurred.");
            System.out.println(e.toString());
        } catch (IllegalChannelException_Exception e) { 
            System.out.println("Expected exception: IllegalChannelException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputDataException_Exception e) { 
            System.out.println("Expected exception: InvalidInputDataException has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking autoMobileCreditEligibleAVP...");
        String _autoMobileCreditEligibleAVP_msisdn = "";
        try {
            String _autoMobileCreditEligibleAVP__return = port.autoMobileCreditEligibleAVP(_autoMobileCreditEligibleAVP_msisdn);
            System.out.println("autoMobileCreditEligibleAVP.result=" + _autoMobileCreditEligibleAVP__return);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getTariffAVP...");
        String _getTariffAVP_msisdn = "";
        try {
            AvayaTariffDTO _getTariffAVP__return = port.getTariffAVP(_getTariffAVP_msisdn);
            System.out.println("getTariffAVP.result=" + _getTariffAVP__return);

        } catch (MsisdnNotFoundException_Exception e) {
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) {
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (AttributesRetrivalException_Exception e) {
            System.out.println("Expected exception: AttributesRetrivalException has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) {
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getCustomerInfoAVP...");
        String _getCustomerInfoAVP_msisdn = "";
        try {
            LbvmcDTO _getCustomerInfoAVP__return = port.getCustomerInfoAVP(_getCustomerInfoAVP_msisdn);
            System.out.println("getCustomerInfoAVP.result=" + _getCustomerInfoAVP__return);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getInetPacksInfoAVP...");
        String _getInetPacksInfoAVP_msisdn = "";
        try {
            java.util.List<InetPackInfoDTO> _getInetPacksInfoAVP__return = port.getInetPacksInfoAVP(_getInetPacksInfoAVP_msisdn);
            System.out.println("getInetPacksInfoAVP.result=" + _getInetPacksInfoAVP__return);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (SoldProductsRetrivalException_Exception e) { 
            System.out.println("Expected exception: SoldProductsRetrivalException has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNearestCustomerCare...");
        String _getNearestCustomerCare_callerPhoneNo = "";
        try {
            java.util.List<Long> _getNearestCustomerCare__return = port.getNearestCustomerCare(_getNearestCustomerCare_callerPhoneNo);
            System.out.println("getNearestCustomerCare.result=" + _getNearestCustomerCare__return);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (MandatoryParameterEmptyException_Exception e) { 
            System.out.println("Expected exception: MandatoryParameterEmptyException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getLastPaymentAVP...");
        String _getLastPaymentAVP_msisdn = "";
        try {
            PaymentDTO _getLastPaymentAVP__return = port.getLastPaymentAVP(_getLastPaymentAVP_msisdn);
            System.out.println("getLastPaymentAVP.result=" + _getLastPaymentAVP__return);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputDataException_Exception e) { 
            System.out.println("Expected exception: InvalidInputDataException has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPinPukAVP...");
        String _getPinPukAVP_msisdn = "";
        try {
           PinPukDTO _getPinPukAVP__return = port.getPinPukAVP(_getPinPukAVP_msisdn);
            System.out.println("getPinPukAVP.result=" + _getPinPukAVP__return);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (SimCardRetrivalException_Exception e) { 
            System.out.println("Expected exception: SimCardRetrivalException has occurred.");
            System.out.println(e.toString());
        } catch (BillingConnectionFailure_Exception e) { 
            System.out.println("Expected exception: BillingConnectionFailure has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking changeTariffAVP...");
        String _changeTariffAVP_msisdn = "";
        Long _changeTariffAVP_tariffId = null;
        try {
            port.changeTariffAVP(_changeTariffAVP_msisdn, _changeTariffAVP_tariffId);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (ProductAlreadySoldException_Exception e) { 
            System.out.println("Expected exception: ProductAlreadySoldException has occurred.");
            System.out.println(e.toString());
        } catch (TariffChangeException_Exception e) { 
            System.out.println("Expected exception: TariffChangeException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (ProductNotFoundException_Exception e) { 
            System.out.println("Expected exception: ProductNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking loadVoucherAVP...");
        String _loadVoucherAVP_msisdn = "";
        String _loadVoucherAVP_secret = "";
        try {
            Double _loadVoucherAVP__return = port.loadVoucherAVP(_loadVoucherAVP_msisdn, _loadVoucherAVP_secret);
            System.out.println("loadVoucherAVP.result=" + _loadVoucherAVP__return);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (ActivateVoucherException_Exception e) { 
            System.out.println("Expected exception: ActivateVoucherException has occurred.");
            System.out.println(e.toString());
        } catch (InvalidInputDataException_Exception e) { 
            System.out.println("Expected exception: InvalidInputDataException has occurred.");
            System.out.println(e.toString());
        } catch (IllegalChannelException_Exception e) { 
            System.out.println("Expected exception: IllegalChannelException has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking setRoamingAVP...");
        String _setRoamingAVP_msisdn = "";
        Boolean _setRoamingAVP_enable = null;
        try {
            port.setRoamingAVP(_setRoamingAVP_msisdn, _setRoamingAVP_enable);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking sendGPRSSettingsAVP...");
        String _sendGPRSSettingsAVP_msisdn = "";
        boolean _sendGPRSSettingsAVP_wap = false;
        boolean _sendGPRSSettingsAVP_internet = false;
        boolean _sendGPRSSettingsAVP_mms = false;
        try {
            port.sendGPRSSettingsAVP(_sendGPRSSettingsAVP_msisdn, _sendGPRSSettingsAVP_wap, _sendGPRSSettingsAVP_internet, _sendGPRSSettingsAVP_mms);

        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking checkPinPukAVP...");
        String _checkPinPukAVP_msisdn = "";
        String _checkPinPukAVP_pinpuk = "";
        try {
            boolean _checkPinPukAVP__return = port.checkPinPukAVP(_checkPinPukAVP_msisdn, _checkPinPukAVP_pinpuk);
            System.out.println("checkPinPukAVP.result=" + _checkPinPukAVP__return);

        } catch (MsisdnNotFoundException_Exception e) { 
            System.out.println("Expected exception: MsisdnNotFoundException has occurred.");
            System.out.println(e.toString());
        } catch (CODAInternalFailure_Exception e) { 
            System.out.println("Expected exception: CODAInternalFailure has occurred.");
            System.out.println(e.toString());
        } catch (SimCardRetrivalException_Exception e) { 
            System.out.println("Expected exception: SimCardRetrivalException has occurred.");
            System.out.println(e.toString());
        } catch (BillingConnectionFailure_Exception e) { 
            System.out.println("Expected exception: BillingConnectionFailure has occurred.");
            System.out.println(e.toString());
        } catch (CbossException_Exception e) { 
            System.out.println("Expected exception: CbossException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
