package com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-12-07T16:03:41.639+02:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", name = "AvayaVoicePortalServicesWS")
@XmlSeeAlso({ObjectFactory.class})
public interface AvayaVoicePortalServicesWS {

    @RequestWrapper(localName = "enableAutoExtraBalanceAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.EnableAutoExtraBalanceAVP")
    @WebMethod
    @ResponseWrapper(localName = "enableAutoExtraBalanceAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.EnableAutoExtraBalanceAVPResponse")
    public void enableAutoExtraBalanceAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws CODAInternalFailure_Exception;


    @RequestWrapper(localName = "addBusinessProductNotifyNewAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.AddBusinessProductNotifyNewAVP")
    @WebMethod
    @ResponseWrapper(localName = "addBusinessProductNotifyNewAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.AddBusinessProductNotifyNewAVPResponse")
    public void addBusinessProductNotifyNewAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "bpId", targetNamespace = "")
                    Long bpId,
            @WebParam(name = "resubscribe", targetNamespace = "")
                    Boolean resubscribe
    ) throws CODAInternalFailure_Exception, AddPromoException_Exception, InvalidInputDataException_Exception, AddBusinessProductException_Exception, IllegalChannelException_Exception, BusinessProductConfigException_Exception, CbossException_Exception;

    @RequestWrapper(localName = "grantMobileCreditAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GrantMobileCreditAVP")
    @WebMethod
    @ResponseWrapper(localName = "grantMobileCreditAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GrantMobileCreditAVPResponse")
    public void grantMobileCreditAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws CODAInternalFailure_Exception, InvalidInputDataException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "mobileCreditEligibleAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.MobileCreditEligibleAVP")
    @WebMethod
    @ResponseWrapper(localName = "mobileCreditEligibleAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.MobileCreditEligibleAVPResponse")
    public String mobileCreditEligibleAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws CODAInternalFailure_Exception, InvalidInputDataException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isInRoaming", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.IsInRoaming")
    @WebMethod
    @ResponseWrapper(localName = "isInRoamingResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.IsInRoamingResponse")
    public Boolean isInRoaming(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws CODAHLRException_Exception;

    @RequestWrapper(localName = "unbarrByPuk", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.UnbarrByPuk")
    @WebMethod
    @ResponseWrapper(localName = "unbarrByPukResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.UnbarrByPukResponse")
    public void unbarrByPuk(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "comments", targetNamespace = "")
                    String comments,
            @WebParam(name = "channel", targetNamespace = "")
                    String channel,
            @WebParam(name = "puk", targetNamespace = "")
                    String puk
    ) throws MsisdnNotFoundException_Exception, MsisdnBarException_Exception, CODAInternalFailure_Exception, IllegalChannelException_Exception, InvalidInputDataException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoamingStateAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetRoamingStateAVP")
    @WebMethod
    @ResponseWrapper(localName = "getRoamingStateAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetRoamingStateAVPResponse")
    public boolean getRoamingStateAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws MsisdnNotFoundException_Exception, CODAInternalFailure_Exception, SoldProductsRetrivalException_Exception;

    @RequestWrapper(localName = "blockAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.BlockAVP")
    @WebMethod
    @ResponseWrapper(localName = "blockAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.BlockAVPResponse")
    public void blockAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws MsisdnNotFoundException_Exception, MsisdnBarException_Exception, CODAInternalFailure_Exception, IllegalChannelException_Exception, InvalidInputDataException_Exception, CbossException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkSubscriberInRoaming", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.CheckSubscriberInRoaming")
    @WebMethod
    @ResponseWrapper(localName = "checkSubscriberInRoamingResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.CheckSubscriberInRoamingResponse")
    public Boolean checkSubscriberInRoaming(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    ) throws MsisdnNotFoundException_Exception, CODAInternalFailure_Exception, CODAHLRException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getBalanceAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetBalanceAVP")
    @WebMethod
    @ResponseWrapper(localName = "getBalanceAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetBalanceAVPResponse")
    public AvayaBalanceDTO getBalanceAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws CODAInternalFailure_Exception, CbossException_Exception;

    @RequestWrapper(localName = "addServiceAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.AddServiceAVP")
    @WebMethod
    @ResponseWrapper(localName = "addServiceAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.AddServiceAVPResponse")
    public void addServiceAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "serviceId", targetNamespace = "")
                    Integer serviceId
    ) throws CODAInternalFailure_Exception, AddPromoException_Exception, IllegalChannelException_Exception, InvalidInputDataException_Exception, CbossException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "autoMobileCreditEligibleAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.AutoMobileCreditEligibleAVP")
    @WebMethod
    @ResponseWrapper(localName = "autoMobileCreditEligibleAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.AutoMobileCreditEligibleAVPResponse")
    public String autoMobileCreditEligibleAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws CODAInternalFailure_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTariffAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetTariffAVP")
    @WebMethod
    @ResponseWrapper(localName = "getTariffAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetTariffAVPResponse")
    public AvayaTariffDTO getTariffAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws MsisdnNotFoundException_Exception, CODAInternalFailure_Exception, AttributesRetrivalException_Exception, CbossException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCustomerInfoAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetCustomerInfoAVP")
    @WebMethod
    @ResponseWrapper(localName = "getCustomerInfoAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetCustomerInfoAVPResponse")
    public LbvmcDTO getCustomerInfoAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws MsisdnNotFoundException_Exception, CODAInternalFailure_Exception, CbossException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInetPacksInfoAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetInetPacksInfoAVP")
    @WebMethod
    @ResponseWrapper(localName = "getInetPacksInfoAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetInetPacksInfoAVPResponse")
    public List<InetPackInfoDTO> getInetPacksInfoAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws MsisdnNotFoundException_Exception, CODAInternalFailure_Exception, SoldProductsRetrivalException_Exception, CbossException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getNearestCustomerCare", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetNearestCustomerCare")
    @WebMethod
    @ResponseWrapper(localName = "getNearestCustomerCareResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetNearestCustomerCareResponse")
    public java.util.List<Long> getNearestCustomerCare(
            @WebParam(name = "callerPhoneNo", targetNamespace = "")
                    String callerPhoneNo
    ) throws CODAInternalFailure_Exception, MandatoryParameterEmptyException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLastPaymentAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetLastPaymentAVP")
    @WebMethod
    @ResponseWrapper(localName = "getLastPaymentAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetLastPaymentAVPResponse")
    public PaymentDTO getLastPaymentAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws CODAInternalFailure_Exception, InvalidInputDataException_Exception, CbossException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPinPukAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetPinPukAVP")
    @WebMethod
    @ResponseWrapper(localName = "getPinPukAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.GetPinPukAVPResponse")
    public PinPukDTO getPinPukAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn
    ) throws MsisdnNotFoundException_Exception, CODAInternalFailure_Exception, SimCardRetrivalException_Exception, BillingConnectionFailure_Exception, CbossException_Exception;

    @RequestWrapper(localName = "changeTariffAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.ChangeTariffAVP")
    @WebMethod
    @ResponseWrapper(localName = "changeTariffAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.ChangeTariffAVPResponse")
    public void changeTariffAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "tariffId", targetNamespace = "")
                    Long tariffId
    ) throws MsisdnNotFoundException_Exception, ProductAlreadySoldException_Exception, TariffChangeException_Exception, CODAInternalFailure_Exception, ProductNotFoundException_Exception, CbossException_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "loadVoucherAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.LoadVoucherAVP")
    @WebMethod
    @ResponseWrapper(localName = "loadVoucherAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.LoadVoucherAVPResponse")
    public Double loadVoucherAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "secret", targetNamespace = "")
                    String secret
    ) throws CODAInternalFailure_Exception, ActivateVoucherException_Exception, InvalidInputDataException_Exception, IllegalChannelException_Exception, CbossException_Exception;

    @RequestWrapper(localName = "setRoamingAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.SetRoamingAVP")
    @WebMethod
    @ResponseWrapper(localName = "setRoamingAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.SetRoamingAVPResponse")
    public void setRoamingAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "enable", targetNamespace = "")
                    Boolean enable
    ) throws CODAInternalFailure_Exception;

    @RequestWrapper(localName = "sendGPRSSettingsAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.SendGPRSSettingsAVP")
    @WebMethod
    @ResponseWrapper(localName = "sendGPRSSettingsAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.SendGPRSSettingsAVPResponse")
    public void sendGPRSSettingsAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "wap", targetNamespace = "")
                    boolean wap,
            @WebParam(name = "internet", targetNamespace = "")
                    boolean internet,
            @WebParam(name = "mms", targetNamespace = "")
                    boolean mms
    ) throws CODAInternalFailure_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "checkPinPukAVP", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.CheckPinPukAVP")
    @WebMethod
    @ResponseWrapper(localName = "checkPinPukAVPResponse", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws", className = "com.omilia.kcell.webservices.CheckPinPukAVPResponse")
    public boolean checkPinPukAVP(
            @WebParam(name = "msisdn", targetNamespace = "")
                    String msisdn,
            @WebParam(name = "pinpuk", targetNamespace = "")
                    String pinpuk
    ) throws MsisdnNotFoundException_Exception, CODAInternalFailure_Exception, SimCardRetrivalException_Exception, BillingConnectionFailure_Exception, CbossException_Exception;
}
