
package com;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-12-07T16:03:41.546+02:00
 * Generated source version: 3.1.1
 */

@WebFault(name = "CODAInternalFailure", targetNamespace = "http://kz.kcell.apps.pentagon.coda.ws")
public class CODAInternalFailure_Exception extends Exception {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -8211225794308857555L;
	private CODAInternalFailure codaInternalFailure;

    public CODAInternalFailure_Exception() {
        super();
    }
    
    public CODAInternalFailure_Exception(String message) {
        super(message);
    }
    
    public CODAInternalFailure_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public CODAInternalFailure_Exception(String message, CODAInternalFailure codaInternalFailure) {
        super(message);
        this.codaInternalFailure = codaInternalFailure;
    }

    public CODAInternalFailure_Exception(String message, CODAInternalFailure codaInternalFailure, Throwable cause) {
        super(message, cause);
        this.codaInternalFailure = codaInternalFailure;
    }

    public CODAInternalFailure getFaultInfo() {
        return this.codaInternalFailure;
    }
}
